plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'com.lenne0815.karoomagicshine'
    compileSdk 35

    buildFeatures {
        compose true
    }

    defaultConfig {
        applicationId "com.lenne0815.karoomagicshine"
        minSdk 26
        targetSdk 34
        versionCode 43
        versionName "2.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation platform('androidx.compose:compose-bom:2024.09.02')
    implementation 'androidx.compose.runtime:runtime'
    implementation 'androidx.compose.ui:ui-graphics'
    implementation 'androidx.compose.ui:ui-unit'
    implementation 'androidx.glance:glance-appwidget:1.1.1'

    implementation("io.hammerhead:karoo-ext:1.1.8")

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0'
    implementation("no.nordicsemi.kotlin.ble:client-android:2.0.0-alpha02")

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.0'
}
